[package]
name = "game"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = "0.33.3"
rapier2d = "0.35.2"
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3.104", features = ["CanvasRenderingContext2d", "HtmlCanvasElement"] }
wgpu = { version = "30.0.0", features = ["webgpu"] }
